apiVersion: v1
kind: Service
metadata:
  name: my-headless-service
  labels:
    app: my-app
spec:
  clusterIP: None  # Headless Service 설정
  ports:
    - port: 80
      name: web
  selector:
    app: my-app
