# External Ingress Controller in AKS
controller:
  service:
    annotations:
      # Azure Load Balancer 헬스 프로브 요청 경로 설정
      service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz
      # 추가적인 Load Balancer 설정이 필요할 경우 여기에 추가
  electionID: external-ingress-controller-leader # 인그레스 컨트롤러의 상태 업데이트를 위한 ID
  ingressClassResource: # 인그레스 클래스 설정
    name: nginx-external # 인그레스 클래스 이름
    enabled: true # 인그레스 클래스 활성화 여부
    default: false # 기본 인그레스 클래스로 설정할지 여부
    controllerValue: "k8s.io/external-ingress-nginx" # 인그레스 컨트롤러의 값
  ingressClass: nginx-external # 하위 버전의 호환성을 위한 설정
