apiVersion: v1
kind: Service
metadata:
  name: mysql-public
  namespace: mysql
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /
spec:
  type: LoadBalancer
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
  sessionAffinity: ClientIP
