apiVersion: v1
kind: Service
metadata:
  name: <SERVICE_NAME>  # 서비스의 이름을 지정합니다.
  namespace: <NAMESPACE>  # 서비스가 배포될 네임스페이스를 지정합니다.
spec:
  type: ClusterIP  # 서비스 유형을 ClusterIP로 설정합니다.
  selector:
    app: <APP_LABEL>  # 서비스가 연결될 파드의 레이블을 지정합니다.
  ports:
    - protocol: TCP  # 프로토콜을 TCP로 설정합니다.
      port: <SERVICE_PORT>  # 서비스가 노출할 포트를 지정합니다.
      targetPort: <TARGET_PORT>  # 파드의 포트를 지정합니다.
