# kubectl create -f values.yaml -n kafka

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: dual-role
  labels:
    strimzi.io/cluster: dtp-kafka
spec:
  replicas: 3
  roles:
    - controller
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 100Gi
        deleteClaim: false
        kraftMetadata: shared
  resources:
    requests:
      cpu: "500m"          
      memory: "1Gi"        
    limits:
      cpu: "2"             
      memory: "4Gi"        
---
 
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: dtp-kafka
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 3.9.0
    metadataVersion: 3.9-IV0
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        type: loadbalancer   
        tls: false           
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: agentpool
                      operator: In
                      values:
                        - agentpool
        tolerations:
          - key: "node-role.kubernetes.io/agentpool"
            operator: "Exists"
            effect: "NoSchedule"
  entityOperator:
    topicOperator: {}
    userOperator: {}
